BUILD_VER=$(date +'%m%d')

LATEST_VER="latest"

MSYS2_VER="20241208"
PYTHON_VER="3.13.1"

ATMO_VER="1.8.0"
ATMO_HASH="c6014b533"
HBL_VER="2.4.4"
HBMENU_VER="3.6.0"

HEKATE_VER="6.2.2"
NYX_VER="1.6.4"

DEEPSEA_VER="4.11.0"
KEFIR_VER="758"
HATS_VER="1.8.0-V1.3"
HATS_HASH="rg6pbf52fvgp4fo"

[latest_version]
ultrahand_version=1.8.2
tester_version=0118
toolkit_version=1.5.1
kip_version=1.5.1
eos_version=1.1.4
mtn_version=2.1.1